# Generated by Django 3.0.4 on 2020-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='scores',
            new_name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
