# Generated by Django 3.0.4 on 2020-03-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200329_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Round'),
        ),
    ]
