# Generated by Django 3.0.4 on 2020-03-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200329_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='polls.Round'),
        ),
    ]
